services:
  db:
    image: postgres:15
    container_name: expense-db
    environment:
      POSTGRES_USER: expenses_user
      POSTGRES_PASSWORD: expenses_password
      POSTGRES_DB: expenses_db
      JWT_SECRET: secretkey123
    ports:
      - "5433:5432"
    volumes:
      - expense-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  api:
    build: ./api
    container_name: expense-api
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: expenses_user
      DB_PASSWORD: expenses_password
      DB_NAME: 
      JWT_SECRET: secretkey123
    depends_on:
      - db
    ports:
      - "3001:3001"

volumes:
  expense-data: