version: '3.9'

services:
  db:
    image: zagrab/work-hours-db:1.0
    container_name: workhours-db
    ports:
      - "5432:5432"
    volumes:
      - workhours-data:/var/lib/postgresql/data

  api:
    image: zagrab/work-hours-api:1.0
    container_name: workhours-api
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: workhours_user
      DB_PASSWORD: workhours_password
      DB_NAME: workhours_db
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  workhours-data:
